### ISSUE TITLE
Error: HttpError: tree.path contains a malformed path component

### ISSUE THREAD

**Issue by nathan815** [grassedge/generate-plantuml-action#24]
When I add a PlantUML diagram to a markdown file the action throws the following error:

```
Error: HttpError: tree.path contains a malformed path component
```

![image](https://user-images.githubusercontent.com/1972782/147896376-9e0c6d53-58b3-4d34-818c-6d44c536c556.png)

Seems to be a GitHub API error. It works perfectly fine for .puml files. Here is my workflow:

```
name: Generate PlantUML
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Also tried with `path: .` set; same error.

The .md file in question:

```
# Test PlantUML Diagram

Sequence diagram:

` ` `plantuml:test-md-diagram
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
` ` `

![](./test-md-diagram.svg)

(rendered diagram should appear above)
```
