### ISSUE TITLE
Unable to generate images on branches

### ISSUE THREAD

**Issue by iozz** [grassedge/generate-plantuml-action#7]
I've managed to setup the action for the `master` branch, but I'd like to also generate images on other branches, so that my reviewers can read our documentation with consistent diagrams during their reviews.

My workflow is the following:

```yaml
name: Generate diagrams
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - uses: actions/checkout@v2
    - name: plantuml
      uses: grassedge/generate-plantuml-action@master
      with:
        path: diagrams
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Unfortunately, it does not work on branches other than `master`, for example on `feat/mvpVersion`:

```
Set up job
Run actions/checkout@v2
remote: Counting objects:  94% (18/19)        
Run actions/checkout@v2
Syncing repository: repo
Getting Git version info
Deleting the contents of '/home/runner/work/repo'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force -B feat/mvpVersion refs/remotes/origin/feat/mvpVersion
  Switched to a new branch 'feat/mvpVersion'
  Branch 'feat/mvpVersion' set up to track remote branch 'feat/mvpVersion' from 'origin'.
/usr/bin/git log -1
commit 712a0ef519c421a60cc9f416f29a01f77ddf2e22
Author: Laurent
Date:   Thu Jun 18 19:13:26 2020 +0200

plantuml
    GITHUB_TOKEN: ***
Run grassedge/generate-plantuml-action@master
There are no files to be generated.
``` 

Did I miss something, or the generation only works on `master`?

**Comment by McNultyyy** [comment]
Not sure if you're still seeing this issue but I'm using the following config and it is generating images for all branches.

```
name: generate plantuml
on:
  push:
    branches:
      - "**"
jobs:
  generate_plantuml: ...
```
